import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const meineSchrift = localFont({
  src: [
    {
      path: "./fonts/Chillax-ExtraLight.ttf",
      weight: "200",
      style: "normal",
    },
    {
      path: "./fonts/Chillax-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/Chillax-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Chillax-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Chillax-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/Chillax-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/Chillax-Variable.ttf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-chillax",
  display: "swap",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${meineSchrift.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
